# This compose file can be used in development to run both the database and app
# within Docker.

version: '3.1'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - mongo
        ports:
            - "9000:9000"
        restart: always
        volumes:
            - ./datas/files:/home/leanote/leanote/files
            - ./datas/upload:/home/leanote/leanote/public/upload
            - ./app.conf:/home/leanote/leanote/conf/app.conf

    mongo:
        image: mongo:4
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: leanote
            MONGO_INITDB_DATABASE: leanote
        volumes:
            - ./mongodb:/data/db
            - ./leanote/mongodb_backup/leanote_install_data:/leanote_install_data
            - ./dbinit.sh:/docker-entrypoint-initdb.d/dbinit.sh
            - ./leanote.js:/leanote.js
